mrs_uav_managers:

  estimation_manager:

    # loaded state estimator plugins
    state_estimators: [
      # "gps_garmin",
      "gps_baro",
    ]

    
    initial_state_estimator: "gps_baro" # will be used as the first state estimator
    agl_height_estimator: "" # only slightly filtered height for checking min height (not used in control feedback)

  control_manager:

  #   # list of names of dynamically loaded trackers
   
    trackers : [
      LineTracker
    ]

  #   # list of names of dynamically loaded controllers
  #   controllers :  "MpcController"
  #
  #
    Se3Controller:
      eland_threshold: 0.1 # [m], position error triggering eland
      failsafe_threshold: 0.1 # [m], position error triggering failsafe land
      odometry_innovation_threshold: 1.5 # [m], position odometry innovation threshold
  uav_manager:

    takeoff:

      rate: 10 # [Hz]

      # during_takeoff:
      #   controller: "MpcController"
      #   tracker: "LandoffTracker"

      # after_takeoff:
      #   controller: "NmpcController"
      #   tracker: "LineTracker"
      takeoff_height: 5.0

    midair_activation:

      after_activation:
        controller: "Se3Controller"
        tracker: "MpcTracker"

      takeoff_height: 5.0
  constraint_manager:

    constraints: [
      "slow",
      "medium",
      "fast",
      "custom",
    ]
    allowed_constraints:
      gps_baro: ["slow", "medium", "fast", "custom"]


    custom:

      horizontal:
        speed: 1.0        # [m/s]
        acceleration: 20.0 # [m/s^2]
        jerk: 800.0        # [m/s^3]
        snap: 800.0        # [m/s^4]

      vertical:

        ascending:
          speed: 1.0        # [m/s]
          acceleration: 20.0 # [m/s^2]
          jerk: 600.0        # [m/s^3]
          snap: 600.0        # [m/s^4]

        descending:
          speed: 1.0        # [m/s]
          acceleration: 20.0 # [m/s^2]
          jerk: 600.0        # [m/s^3]
          snap: 600.0        # [m/s^4]

      heading:
        speed: 0.5        # [rad/s]
        acceleration: 20.0 # [rad/s^2]
        jerk: 400.0        # [rad/s^3]
        snap: 400.0        # [rad/s^4]

      angular_speed:
        roll: 120.0  # [rad/s]
        pitch: 120.0 # [rad/s]
        yaw: 10.0   # [rad/s]

      tilt: 90.0 # [deg]

    default_constraints:
      gps_baro: "custom"

  # gain_manager:

  #   soft:

  #     horizontal:
  #       kp: 6.0
  #       kv: 3.0
  #       ka: 2.0

  #       kib: 0.1
  #       kib_lim: 5.0

  #       kiw: 0.1
  #       kiw_lim: 5.0

  #     vertical:
  #       kp: 15.0
  #       kv: 8.0
  #       ka: 2.0

  #     attitude:
  #       kq_roll_pitch: 5.0
  #       kq_yaw: 5.0

  #     mass_estimator:
  #       km: 0.5

  #       # the maximum estimated uav mass difference
  #       km_lim: 20.0 # [kg, at least 1/2 of the UAVs mass to allow landing detection]
mrs_uav_trajectory_generation:

  # execution time limiter
  max_time: 0.5 # [s]

  # check and fix the max deviation between the input path and the output trajectory
  # by subsampling the original path with more waypoints
  
  # check_trajectory_deviation:
  #   max_deviation: 0.20 # [m]

  # allows to neglect waypoints in the original path if the new path
  # does not violate max distance from the original path.
  # This makes for similar but sparser paths, which are easier for the
  # trajectory generator to work with.
  # path_straightener:
  #   enabled: true
  #   max_deviation: 0.20 # [m]



mrs_uav_trackers:

  mpc_tracker:

    wiggle:
      enabled: false
      amplitude: 0.5 # [m]
      frequency: 0.2 # [Hz]

    # mrs collision avoidance
    collision_avoidance:

      enabled:           false # disabling this will stop this UAV to react to others, but it will still transmit data to others
      enabled_passively: false # disabling this will stop this uav to even transmit its data to others (only if enabled: false)
      radius: 5.0 # [m]
      correction: 3.0 # [m]

  line_tracker:

    tracker_loop_rate: 100 # [Hz]

    horizontal_tracker:
      horizontal_speed: 8.0
      horizontal_acceleration: 20.0

    vertical_tracker:
      vertical_speed: 8.0
      vertical_acceleration: 20.0

    heading_tracker:
      heading_gain: 10.0
      heading_rate: 5
