livox:
  tilt_deg: 20.0
  fov:  59.0

group_odoms:
  enable: 

rbl_controller:
  only_2d: false
  z_min: 1.0
  z_max: 10.0
  z_ref: 1.0
  d1: 0.5
  d2: 0.5
  d3: 0.5
  d4: 0.5 
  d5: 0.5
  d6: 1.0
  d7: 0.2
  radius: 3.5
  encumbrance: 0.5
  step_size: 0.35
  betaD: 0.1
  beta_min: 0.1
  use_z_rule: false
  dt: 0.1
  cwvd_rob: 0.9
  cwvd_obs: 0.9
