simulation_rate: 100.0
clock_rate: 100.0
realtime_factor: 1.0

individual_takeoff_platform:
  enabled: false

collisions:
  enabled: true
  crash: false

  # if crash==false, then the collisions are elastic
  rebounce: 0.0

# randomization of the initial conditions around the desired spawn point
randomization:

  enabled: false

  bounds:
    x: 15.0
    y: 15.0
    z: 15.0

ground:
  enabled: true
  z: 0.0 # [m]
#


uav_names: [
  "uav1",
  "uav2",
  "uav3",
  "uav4",
  "uav5",  
  # "uav6",
  # "uav7",
  # "uav8",  
  # "uav9",
  # "uav10",
]

uav1:
  type: "x500"
  spawn:
    x: 10.00
    y: 0.00
    z: 5.00
    heading: -3.14

uav2:
  type: "x500"
  spawn:
    x: 3.09
    y: 9.51
    z: 5.00
    heading: -4.40

uav3:
  type: "x500"
  spawn:
    x: -8.09
    y: 5.88
    z: 5.00
    heading: -5.65

uav4:
  type: "x500"
  spawn:
    x: -8.09
    y: -5.88
    z: 5.00
    heading: -6.91

uav5:
  type: "x500"
  spawn:
    x: 3.09
    y: -9.51
    z: 5.00
    heading: -8.17


