mrs_uav_managers:

  estimation_manager:

    # loaded state estimator plugins
    state_estimators: [
      "gps_baro",
      # "rtk",
    ]

    initial_state_estimator: "gps_baro" # will be used as the first state estimator
    agl_height_estimator: "" # only slightly filtered height for checking min height (not used in control feedback)

  control_manager:

    safety:

      tilt_limit:

        eland:
          enabled: false

        disarm:
          enabled: false

      tilt_error_disarm:
        enabled: false

      yaw_error_eland:
        enabled: false

    # ExampleTracker:
    #   address: "example_tracker_plugin/ExampleTracker"
    #   namespace: "example_tracker"
    #   human_switchable: true

    # # list of names of dynamically loaded trackers
    # trackers : [
    #   "ExampleTracker",
    # ]

    NmpcController:
      address: "controller_module/ControllerModule"
      namespace: "controller_module"
      eland_threshold: 0.0 # [m], position error triggering eland
      failsafe_threshold: 0.0 # [m], position error triggering failsafe land
      odometry_innovation_threshold: 0 # [m], position odometry innovation threshold
      human_switchable: true

      # which outputs the controller can provide
      outputs:
        actuators:             false
        control_group:         false
        attitude_rate:         true
        attitude:              false
        acceleration_hdg_rate: false
        acceleration_hdg:      false
        velocity_hdg_rate:     false
        velocity_hdg:          false
        position:              false 

    # list of names of dynamically loaded controllers
    controllers : [
      "NmpcController",
    ]


  uav_manager:

    takeoff:

      rate: 10 # [Hz]

      during_takeoff:
        controller: "NmpcController"
        tracker: "LandoffTracker"

      after_takeoff:
        controller: "NmpcController"
        tracker: "MpcTracker"

      takeoff_height: 5

    min_height_checking:
      enabled: false

    max_height_checking:
      enabled: false

  constraint_manager:

    superfast:

      horizontal:
        speed: 20.0
        acceleration: 40.0
        jerk: 1000.0
        snap: 1000.0

      vertical:

        ascending:
          speed: 20.0
          acceleration: 40.0
          jerk: 1000.0
          snap: 1000.0

        descending:
          speed: 20.0
          acceleration: 40.0
          jerk: 1000.0
          snap: 1000.0

      heading:
        speed: 4.0
        acceleration: 4.0
        jerk: 1000.0
        snap: 1000.0

      angular_speed:
        roll: 6000.0
        pitch: 6000.0
        yaw: 100.0

      tilt: 180.0 # [deg]

    estimator_types: [
      "gps_baro",
      "other",
      "ground_truth",
      "passthrough",
    ]

    constraints: [
      "slow",
      "medium",
      "fast",
      "superfast",
    ]

    # list of allowed constraints per odometry mode
    allowed_constraints:
      gps_garmin: ["slow", "medium", "fast", "superfast"]
      gps_baro: ["slow", "medium", "fast", "superfast"]
      rtk: ["slow", "medium", "fast"]
      rtk_garmin: ["slow", "medium", "fast"]
      other: ["slow"]
      ground_truth: ["slow", "medium", "fast", "superfast"]
      passthrough: ["slow", "medium", "fast", "superfast"]

    # those constraints will be used automatically when a localization mode switches
    # and the current constraints are not in the allowed list (next paragraphs)
    default_constraints:
      gps_garmin: "medium"
      gps_baro: "superfast"
      other: "slow"
      ground_truth: "superfast"
      passthrough: "medium"

mrs_uav_trackers:

  mpc_tracker:
    # mrs collision avoidance
    collision_avoidance:

      enabled:           false # disabling this will stop this UAV to react to others, but it will still transmit data to others

mrs_uav_controllers:

  controller_module:

    nmpc:

      uav_configuration:

        mass: 1.21        # [kg]
        # arm_length: 0.15  # [m]
        mot0_pos: [ 0.15,  -0.15]
        mot1_pos: [-0.15,  0.15]
        mot2_pos: [-0.15, -0.15]
        mot3_pos: [ 0.15,  0.15]
        inertia: [0.007, 0.007, 0.010] # diag(xx, yy, zz)
        ctau: 0.012 # [] thrust torque coefficient
        drag: [0.38, 0.47, 1.5] # [] linear air drag coefficient
        voltage_based_thrustmap: True
        propulsion_module_config: src/propulsion_module/scripts/motor_science/alien_a300.yaml


        # acados settings
      solver:

        ac_num_iter: 20 # [-]
        ac_horizon: 1 # [s]
        ac_time_steps: [0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05]

      costs:

        Q_position_xy: 100
        Q_position_z: 100
        Q_rotation_xy: 26
        Q_rotation_z: 100
        Q_velocity: 6
        Q_omega: 26
        # R_matrix: (relative importance)
        R_thrust: 4

      uav_constraints:

        thrust_max: 17 # [N] per motor, max for a300 is rather 20
        thrust_min: 0.5 # [N] per motor
        thrust_total_max: 53.4 # [N]
        thrust_total_min: 2.0 # [N]
        max_rot_speed: [6.0, 6.0, 3] # roll, pitch, yaw [rad/s]

    rk4:

      controller_dt: 0.01 # [s]
      mem_num: 0 # number of integration in feed forward.

    optional:

      verbose: False
      warn_too_high_body_rates: False
      warn_body_rates: [5,5,1]

